- name: configure the backend
  hosts: backend
  become: yes
  vars:
    mysql_passd: ExpenseApp@1
    login_host: mysql.joinsankardevops.online
  tasks:
    - name: disable default nodejs
      ansible.builtin.command:
        cmd: dnf module disable nodejs -y

    - name: enable nodejs 20
      ansible.builtin.command:
        cmd: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs  # Fixed the package name, removing the space
        state: present  # Fixed spelling from "prasent" to "present"

    - name: create user
      ansible.builtin.user:
        name: expense

    - name: create app directory
      ansible.builtin.file:
       path: /app
       state: directory


    - name: download the backend code
      ansible.builtin.get_url:
       url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
       dest: /tmp/backend.zip

    - name: extract the code
      ansible.builtin.unarchive:
       src: /tmp/backend.zip #by default ansible thinks this is in ansible server
       dest: /app
       remote_src: yes  

    - name: install dependencies
      ansible.builtin.command: npm install
       args:
       chdir: /app 

    - name: copy the service file
      ansible.builtin.copy:
       src: backend.service
       dest: /etc/systemd/system/backend.service   


    - name: import mysql data
      community.mysql.mysql_db:
       login_user: root
       login_password: "{{ mysql_root_password }}"
       login_host: "{{ login_host }}"
       target: /app/schema/backend.sql
       name: all
       state: dump
   