- name: mysql configuration
  hosts: mysql
  become: yes
  tasks:
    - name: installing mysql server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: enable mysqld
      ansible.builtin.service:
        name: mysql
        state : started
        enabled: yes    

